server:
    port: 8200
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/safecntr?useUnicode=true&serverTimezone=GMT%2B8
        username: root
        password: root
    tipper:
        base: tips/
